version: '3.8'

services:
  # Câu 81, 83, 85: Khai báo Service Backend, Port và Biến môi trường
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb+srv://viho317_db_user:Hdv2005@cluster0.ekxyz7q.mongodb.net/cloud_lab?appName=Cluster0

  # Câu 82, 84: Khai báo Service Frontend và Port
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend