services:
  backend:
    image: hodaivi/mern-backend:1.0
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb+srv://viho317_db_user:Hdv2005@cluster0.ekxyz7q.mongodb.net/cloud_lab?appName=Cluster0
    network_mode: bridge

  frontend:
    image: hodaivi/mern-frontend:2.0
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    network_mode: bridge